### ISSUE TITLE
Check README for grammar

### ISSUE THREAD

**Issue by aron123** [aron123/node-barion#20]
I'm not native speaker of English, so checking the README for grammatic mistakes (and typos) would be much appreciated.

**Comment by dkapur17** [comment]
I would like to contribute to this if possible. TIA.

**Comment by swagatikapanda123** [comment]
i want to work on this

**Comment by aron123** [comment]
#21 , #22 , #23

**Comment by carnationcrab** [comment]
https://github.com/aron123/node-barion/pull/24 Should be completed in this PR.
