### ISSUE TITLE
The redirect url is required!

### ISSUE THREAD

**Issue by LaKing** [aron123/node-barion#29]
Probably a documentation bug. The parameter is not optional.

When using the default example:
```
errors:
[ { Title: 'Model Validation Error',
Description: 'The redirect url is required!',
ErrorCode: 'ModelValidationError',
HappenedAt: '2020-04-02T01:54:16.0574019Z',
EndPoint: 'https://api.test.barion.com/v2/Payment/Start' } ] }
```

**Comment by aron123** [comment]
This is a modification of the Barion API, that I forgot to implement and document. I'll fix the schema and the README in 1-2 days.

Thanks for the report.

**Comment by aron123** [comment]
I've investigated a bit and there is the explanation for this inconsistency with Barion Docs:

Earlier the default redirect URL can be specified in Barion account's admin panel. Later Barion removed this setting from the admin panel, and started to get the redirect URL only in the "payment start" API call. But for backward compatibility, they already store the former default redirect URLs that are set in admin panel and use it if the API caller does not provide any redirect URL in their request.

So from `node-barion` module's view, the 'RedirectUrl' is still optional. If I change it, it can break implementations that are currently deal with the redirect URL set in the old admin panel.

**Comment by aron123** [comment]
Otherwise, I'll update the code example to show the best practice.

**Comment by LaKing** [comment]
Thank you.
