### ISSUE TITLE
Are Recurring payments supported?

### ISSUE THREAD

**Issue by axos88** [aron123/node-barion#31]
It is possible to repeat a payment at a later date?

**Comment by aron123** [comment]
Hi Ákos,

`node-barion` supports all the functionality that Barion API provides, as well as recurring payments.

You can read about recurring or token payment [here](https://docs.barion.com/Token_payment). After that, you can use the `startPayment` and `getPaymentState` methods of `node-barion` to implement the payment process in your system.

**Comment by axos88** [comment]
Thanks, Aron, I'll look into it!
