### ISSUE TITLE
Is this repo still maintained?

### ISSUE THREAD

**Issue by villszer** [aron123/node-barion#77]
Hi all!

I'm looking a library to integrate barion to my node.js project.
I'm wondering if this library is still usable and maintaned.

Thank you very much!

**Comment by aron123** [comment]
For a while, I haven't have enough time to follow Barion API changes, so
the library might not be up-to-date for certain endpoints.

But the good news is PRs are welcome, so everybody can fix it, I will merge
the changes. :)

villszer ***@***.***> ezt írta (időpont: 2024. febr. 1., Cs
21:27):

**Comment by villszer** [comment]
Thank you very much for your response!
I will test it in the following days and let you know if i find something that is not up-to-date.
Ofc i will try to do a PR if this is the case.

Thank you,
