### ISSUE TITLE
The TransactionToFinish should accept zero for closure

### ISSUE THREAD

**Issue by dersy90** [aron123/node-barion#81]
The current implementation of TransactionToFinish (/lib/domain/common) does not allow the completion of a reservation with a zero (0) amount, as the Total field is validated with a .greater(0) condition. However, according to the Barion API documentation, completing the transaction with zero is the correct way to execute a full refund for facilitated payments.

Justification:

The Barion API documentation specifically states that the total refund can be executed by providing a zero amount during the completion of the reservation:

Refunding facilitated payments
When using facilitated payments, refund is a special case. As long as a reservation payment is not finished, the facilitator has complete control of the process and is able to refund the amount by finishing the payment transactions with zero amount. However, in case of a completed immediate or a finished reservation payment, the facilitator no longer has control over the process. This means that incurring refunds must be done by the seller. The facilitator and the seller must ensure the legal compliance of this in their respective environment.

Suggestion: The following modification is proposed for the TransactionToFinish validation schema:

Change the validation of the Total field from .greater(0) to .greater(-1) to allow closure with zero.
This will ensure that full refunds can be executed for facilitated payments according to the appropriate rules.

**Comment by aron123** [comment]
Thank you for the detailed report. I will try to release a new hotfix release this weekend.

**Comment by aron123** [comment]
@dersy90 Could you open a PR with your modifications? I see you fixed it in your fork.

**Comment by dersy90** [comment]
I opened it :)

**Comment by aron123** [comment]
node-barion@3.2.0 is released. Thank you for resolving this bug.
